### PR TITLE
Speedup ec.recoverPubKey

### PR DESCRIPTION
**Pull request by fanatid**
Similar to https://github.com/cryptocoinjs/secp256k1-node/pull/101
should be ~2x faster

### CODE REVIEW

**Comment by indutny** [comment]
Benchmarks? :)

**Comment by fanatid** [comment]
```js
var EC = require('elliptic').ec
var secp256k1 = new EC('secp256k1')

var R = secp256k1.genKeyPair().getPublic()
var e = secp256k1.genKeyPair().getPrivate()
var s = secp256k1.genKeyPair().getPrivate()
var rinv = secp256k1.genKeyPair().getPrivate()

var cnt = 5e2

console.time('1 point mul')
for (var i = 0; i < cnt; ++i) {
  secp256k1.g.mulAdd(e, R, s).mul(rinv)
}
console.timeEnd('1 point mul')

console.time('2 scalar mul')
for (var i = 0; i < cnt; ++i) {
  secp256k1.g.mulAdd(e.mul(rinv).umod(secp256k1.n), R, s.mul(rinv).umod(secp256k1.n))
}
console.timeEnd('2 scalar mul')
```

```
1 point mul: 3057.023ms
2 scalar mul: 1855.858ms
```

**Comment by indutny** [comment]
Ok, I'm convinced. Thank you!

**Comment by indutny** [comment]
Landed in f3edfe5, and released in 6.3.2. Thank you!

**Pull request closed without merging**
