### PR TITLE
Avoid circular dependency

### PR DESCRIPTION
**Pull request by xg-wang**
Circular dependency is causing undefined export for bundling tools like rollup to have issue with building UMD modules.

### CODE REVIEW

**Comment by xg-wang** [comment]
Failed tests seem irrelevant.

**Comment by iantanwx** [comment]
@indutny do you plan to merge this PR?

**Comment by spiceboi** [comment]
Would also like this merged

**Comment by gavinpatkinson** [comment]
Has there been any progress on this?

**Comment by ClemensLey** [comment]
I have the same problem. There is a fork with one big commit that removes circular dependencies but I could not get it to work:
https://github.com/xg-wang/elliptic

Suggestions highly appreciated

**Comment by iantanwx** [comment]
https://github.com/Zilliqa/Zilliqa-JavaScript-Library/blob/master/scripts/bundle.ts is the workaround I’ve been using. Not ideal, but it works.

**Comment by shrpne** [comment]
@indutny can you merge it, please?
This Rollup  issue is still active: https://github.com/rollup/rollup-plugin-commonjs/issues/278
Some use webpack to workaround it, but it produces less optimal build

**Comment by indutny** [comment]
Sorry for very long delay. I'd be happy to merge the PR if someone is willing to rebase it.

**Comment by xg-wang** [comment]
Sorry I no longer use this library. If anyone rebased the pr feel free to close it.

**Comment by shrpne** [comment]
@indutny done in the #180

**Pull request closed without merging**
