### PR TITLE
No longer requires package.json for version number

### PR DESCRIPTION
**Pull request by lorem--ipsum**
Referring to https://github.com/indutny/elliptic/issues/106

### CODE REVIEW

**Comment by fanatid** [comment]
@lorem--ipsum why not projects from https://github.com/indutny/elliptic/issues/106#issuecomment-258108800 ? IMHO they better than string replace

**Comment by Chris-Boyle** [comment]
@lorem--ipsum @indutny what's the status on this PR?  I ran into an issue where elliptic is pulled into my project exposing my local path in the bundled asset and elliptic's package.json is also bloating the bundled asset.

**Comment by lorem--ipsum** [comment]
@Chris-Boyle No idea, can barely remember what this is about...

**Comment by fanatid** [comment]
@Chris-Boyle why not use https://github.com/fanatid/browserify-package-json / https://github.com/headfire94/package-json-cleanup-loader ?

**Comment by thgreasi** [comment]
Any update on this?

**Pull request closed without merging**
