### PR TITLE
Added build task for browsers

### PR DESCRIPTION
**Pull request by sorgloomer**
I've found a broken build task in gruntfile.js, and this is my humble attempt to fix it. Creates dist/elliptic.js and dist/elliptic.min.js using browserify and uglify. The dist folder is gitignored.

### CODE REVIEW

**Comment by fanatid** [comment]
Why not add build task to package.json:scripts?
@indutny I think we can remove grunt if will use [zuul](https://github.com/defunctzombie/zuul), I did this yesterday with tape..

**Comment by sorgloomer** [comment]
I can add a "browser": "grunt build" script to the package.json if you wish.

I think its a matter of taste. I dont like to use package.json scripts to tasks with more than a single command, because it's hard to maintain the multiplatform support for builds. The other day I saw scripts like "browserify && uglify" somewhere, that obviously didn't work on windows, had to run them manually. So i'd prefer grunt/gulp or at least simple js scripts (but not shell scripts or batch files) to "concatenate" tasks.

**Comment by fanatid** [comment]
@sorgloomer you can use [npm-run-all](https://www.npmjs.com/package/npm-run-all)

**Comment by indutny** [comment]
Yikes, sorry! Looks like I fixed this myself accidentally, without looking at this PR. Sorry!

The fix is here: 1b60ef4

**Pull request closed without merging**
