### PR TITLE
ecdsa: allow passing custom K for signing

### PR DESCRIPTION
**Pull request by indutny**
Fix: #68 

cc @fanatid

### CODE REVIEW

**Comment by fanatid** [comment]
Nice solution! What about pass attempt number to `options.k`?

btw, small improvement in `.sign`:
```js
  var bytes = this.n.byteLength();
  var bkey = key.getPrivate().toArray();
  for (var i = bkey.length; i < bytes; i++)
    bkey.unshift(0);
```
to
```js
var bkey = key.getPrivate().toArray(null, this.n.byteLength());
```
(same for nonce)

**Comment by indutny** [comment]
Landed in 9fc874c . `options.k(iter)` should return `bn.js` instance indeed, it will be truncated if it is bigger than curve's `n` parameter. Otherwise it will try to use it as it is.

Please be aware that it is extremely important that the `k` should be never repeated when using the same private key and different messages. If there will ever be the same `k` - the private key could be easily extracted out of the signatures. This is the reason why I'm using HMAC-DRBG by default.

**Comment by indutny** [comment]
Regarding optimizations - may I ask you to submit a PR with these changes?

**Comment by dcousens** [comment]
@indutny awesome :+1:

**Comment by fanatid** [comment]
done in #70

**Pull request closed without merging**
