### PR TITLE
Avoid circular dependency

### PR DESCRIPTION
**Pull request by shrpne**
Here are changes from #157 rebased to master

### CODE REVIEW

**Comment by lemoustachiste** [comment]
I am having conflicts now between dependencies as some install 6.4.1 and the fix by @xg-wang is for 6.4.0. Could we merge this to regain sanity? Elliptic is a subdependency of my project and I don't have direct control over it.

Thanks a lot

**Comment by shrpne** [comment]
@lemoustachiste you can try to install required elliptic version as a dependency of your project and then run `npm dedupe elliptic` it should replace all elliptic version with your installed version

**Comment by lemoustachiste** [comment]
yes that's what I am doing now and it works fine. But it's a bit tedious.

**Comment by shrpne** [comment]
@indutny friendly reminder that PR is ready to be merged :)

**Comment by indutny** [comment]
Landed in dbe8bc6 and released in 6.5.0. Thank you, and sorry for delay!

**Pull request closed without merging**
