### PR TITLE
Update bn.js to address Buffer deprecation

### LINKED ISSUE #196: DeprecationWarning on Buffer
I see the below warning on Node.js 10.x and 12.x
`[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

`new Buffer(size)` had been deprecated in Node.js 6.0.0 back in 2016-04-26.
https://nodejs.org/api/buffer.html#buffer_new_buffer_size

I suspect these lines 
https://github.com/indutny/elliptic/blob/71e4e8e2f5b8f0bdbfbe106c72cc9fbc746d3d60/dist/elliptic.js#L4367
https://github.com/indutny/elliptic/blob/71e4e8e2f5b8f0bdbfbe106c72cc9fbc746d3d60/dist/elliptic.js#L4382

### PR DESCRIPTION
**Pull request by exoego**
Closes #196

### CODE REVIEW

**Comment by exoego** [comment]
Hmm, some tests failed due to [this changes in bn.js](https://github.com/indutny/bn.js/pull/173).
How should these tests be addressed?
Does this indicated an issue in elliptic, or in bn.js ?

**Comment by fanatid** [comment]
`package-lock.json` should not be added. There still no decision how this should be handled. See #191

**Comment by exoego** [comment]
Hello core developers, how should I proceed this and related PRs?

**Comment by exoego** [comment]
@fanatid 
Updated `bn.js` to `5.1.1` since [newer version have been released](https://github.com/indutny/bn.js/blob/master/CHANGELOG.md) while waiting review.

**Comment by exoego** [comment]
Closing as a duplicate, since a maintainer opened a same PR in #210

**Pull request closed without merging**
