### PR TITLE
No longer requires package.json

### PR DESCRIPTION
**Pull request by DevSide**
Because #133 was not merged.
Issue #106

I used **browserify-versionify** instead of **package-json-versionify** which does too much stuff and produces a very short module.

### CODE REVIEW

**Comment by dcousens** [comment]
NACK,  you add the complexity of another dependency.

Compared to the import of __existing code__,  with the eventual burden of only 50 LOC in your browserify build?

**Comment by DevSide** [comment]
What do you mean ?

**Comment by dcousens** [comment]
@DevSide I don't use browserify dist... wouldn't importing this in `node` force the `lib` import to fail?

**Comment by dcousens** [comment]
After reading into #106... this does seem a bit cludgy.
Additionally,  how would this work without using the `dist/` for import?

**Comment by DevSide** [comment]
What's the use case of having the version exportable ? Could we just add append a comment with it in dist generated files ?

**Comment by DevSide** [comment]
Could we just append a comment in dist generated files ?

**Pull request closed without merging**
