### PR TITLE
key: explicit methods for priv/pub/object

### LINKED ISSUE #21: query: curve25519-donna
i have been looking around for a pure-javascript implementation of the "donna" -- https://code.google.com/p/curve25519-donna/ & http://cr.yp.to/ecdh.html

i have a sneaking suspicion that this is implemented in elliptic, although with a slightly different API/naming convention. am i right or just optimistic?

sorry for the lack of clue. thanks!

### PR DESCRIPTION
**Pull request by indutny**
fix #21

@ryanxcharles how does this look to you guys? Should remove lots of uncertainty from the code.

### CODE REVIEW

**Comment by mrose17** [comment]
+1

**Comment by dcousens** [comment]
+1 I'm very happy with these changes.

**Comment by jprichardson** [comment]
Yeah, this definitely makes it much nicer to work with!

**Comment by indutny** [comment]
cc @braydonf too

**Comment by braydonf** [comment]
LGTM

I've tested these changes with [Bitcore](https://github.com/bitpay/bitcore) and it can upgraded without any changes. With [BitAuth](https://github.com/bitpay/bitauth) two lines would need to be changed:

```patch
@@ -33,11 +33,11 @@ BitAuth.generateSin = function() {
  * @param {String} A private key in hex
  * @returns {String} A compressed public key in hex
  */
 BitAuth.getPublicKeyFromPrivateKey = function(privkey) {
 
-  var keys = ecdsa.keyPair(privkey, 'hex');
+  var keys = ecdsa.keyFromPrivate(privkey, 'hex');
 
   // compressed public key
   var pubKey = keys.getPublic();
   var xbuf = new Buffer(pubKey.x.toString('hex', 64), 'hex');
   var ybuf = new Buffer(pubKey.y.toString('hex', 64), 'hex');
@@ -112,11 +112,11 @@ BitAuth.sign = function(data, privkey) {
  * @returns {Function|Boolean} - If the signature is valid
  */
 BitAuth.verifySignature = function(data, pubkey, hexsignature, callback) {
   var hash = (new hashjs.sha256()).update(data).digest('hex');
   var signature = new Buffer(hexsignature, 'hex');
-  var valid = ecdsa.verify(hash, signature, pubkey);
+  var valid = ecdsa.verify(hash, signature, pubkey, 'hex');
   if (callback)
     return callback(null, valid);
   return valid;
 };
 ```

It looks like the format of the pubkey in verify was assumed to be 'hex' before, and now it needs to be explicitly set.

**Comment by indutny** [comment]
Landed and pushed in 2.0.0, because of the API change.

**Comment by mrose17** [comment]
+1 - many thanks!

**Pull request merged**
